---
version: '2'
catalog:
    name: "GeoNode generic"
    version: "v2.0"
    description: "Generic GeoNode deployment - with sidekicks"
    uuid: geonode-generic-0
    minimum_rancher_version: 'v1.6'

    questions:
        - variable: "EXPOSED_HTTP_PORT"
          label: "External ngxin port"
          description: |
                Port number on which nginx from this deployment will
                be visible on the host. If you have multiple stacks or nginx
                or load balancer running on host, you should set distinct
                port here.
          default: 80
          required: true
          type: "int"
        - variable: "ALLOWED_HOSTS"
          label: "List of allowed host header values"
          description: |
                List of host header values which should be
                permitted. You should add full-qualified domain
                names under which deployment is visible. Default
                values, django and geonode values are
                added internally.
          required: true
          type: string
          default: "[]"

        - variable: "SITEURL"
          label: "Default URL for site"
          description: |
                URL to default location of site. It will be used
                to construct absolute urls.
          required: true
          type: 'string'
          default:

        - variable: "SITENAME"
          label: "Name of site"
          description: |
                Name of the site to be used in title
          required: false
          default: "GeoNode"
          type: string

        - variable: "ADMIN_EMAILS"
          label: "List of admin emails"
          description: |
                List of emails of admins, who should
                receive notifications. Entries
                should be separated with coma.
          required: false
          type: string
          default:

        - variable: "HOST_AFFINITY"
          label: "Label of host to deploy on"
          description: |
                To keep containers running on specific
                hosts, provide label attached to host
                to deploy on.
          required: true
          type: string
          default:

services:
    db:
        scale: 1
    django:
        retain_ip: true
        scale: 1
    geoserver:
        scale: 1
    geonode:
        scale: 1
        labels:
            io.rancher.sidekicks: db, django, geoserver, data-dir-conf
    data-dir-conf:
        labels:
            io.rancher.container.start_once: true        
        scale: 1

